export const COLOMBIAN_REGIONS: { label: string; value: string }[] = [
  { label: '🇨🇴 Amazonas', value: 'Amazonas' },
  { label: '🇨🇴 Antioquia', value: 'Antioquia' },
  { label: '🇨🇴 Arauca', value: 'Arauca' },
  { label: '🇨🇴 Atlántico', value: 'Atlántico' },
  { label: '🇨🇴 Bogotá D.C.', value: 'Bogotá D.C.' },
  { label: '🇨🇴 Bolívar', value: 'Bolívar' },
  { label: '🇨🇴 Boyacá', value: 'Boyacá' },
  { label: '🇨🇴 Caldas', value: 'Caldas' },
  { label: '🇨🇴 Caquetá', value: 'Caquetá' },
  { label: '🇨🇴 Casanare', value: 'Casanare' },
  { label: '🇨🇴 Cauca', value: 'Cauca' },
  { label: '🇨🇴 Cesar', value: 'Cesar' },
  { label: '🇨🇴 Chocó', value: 'Chocó' },
  { label: '🇨🇴 Córdoba', value: 'Córdoba' },
  { label: '🇨🇴 Cundinamarca', value: 'Cundinamarca' },
  { label: '🇨🇴 Guainía', value: 'Guainía' },
  { label: '🇨🇴 Guaviare', value: 'Guaviare' },
  { label: '🇨🇴 Huila', value: 'Huila' },
  { label: '🇨🇴 La Guajira', value: 'La Guajira' },
  { label: '🇨🇴 Magdalena', value: 'Magdalena' },
  { label: '🇨🇴 Meta', value: 'Meta' },
  { label: '🇨🇴 Nariño', value: 'Nariño' },
  { label: '🇨🇴 Norte de Santander', value: 'Norte de Santander' },
  { label: '🇨🇴 Putumayo', value: 'Putumayo' },
  { label: '🇨🇴 Quindío', value: 'Quindío' },
  { label: '🇨🇴 Risaralda', value: 'Risaralda' },
  { label: '🇨🇴 San Andrés y Providencia', value: 'San Andrés y Providencia' },
  { label: '🇨🇴 Santander', value: 'Santander' },
  { label: '🇨🇴 Sucre', value: 'Sucre' },
  { label: '🇨🇴 Tolima', value: 'Tolima' },
  { label: '🇨🇴 Valle del Cauca', value: 'Valle del Cauca' },
  { label: '🇨🇴 Vaupés', value: 'Vaupés' },
  { label: '🇨🇴 Vichada', value: 'Vichada' },
]

/** Valores simples de departamento (sin emoji) para selects de turismo */
export const DEPARTAMENTOS_COLOMBIA: string[] = COLOMBIAN_REGIONS.map((r) => r.value)

/** Los 125 municipios del departamento de Antioquia */
export const MUNICIPIOS_ANTIOQUIA: string[] = [
  'Abejorral',
  'Abriaquí',
  'Alejandría',
  'Amagá',
  'Amalfi',
  'Andes',
  'Angelópolis',
  'Angostura',
  'Anorí',
  'Apartadó',
  'Arboletes',
  'Argelia',
  'Armenia',
  'Barbosa',
  'Bello',
  'Belmira',
  'Betania',
  'Betulia',
  'Briceño',
  'Buriticá',
  'Cáceres',
  'Caicedo',
  'Caldas',
  'Campamento',
  'Cañasgordas',
  'Caracolí',
  'Caramanta',
  'Carepa',
  'Carolina del Príncipe',
  'Caucasia',
  'Chigorodó',
  'Cisneros',
  'Cocorná',
  'Concepción',
  'Concordia',
  'Copacabana',
  'Dabeiba',
  'Donmatías',
  'Ebéjico',
  'El Bagre',
  'El Carmen de Viboral',
  'El Peñol',
  'El Retiro',
  'El Santuario',
  'Entrerríos',
  'Envigado',
  'Fredonia',
  'Frontino',
  'Giraldo',
  'Girardota',
  'Gómez Plata',
  'Granada',
  'Guadalupe',
  'Guarne',
  'Guatapé',
  'Heliconia',
  'Hispania',
  'Itagüí',
  'Ituango',
  'Jardín',
  'Jericó',
  'La Ceja',
  'La Estrella',
  'La Pintada',
  'La Unión',
  'Liborina',
  'Maceo',
  'Marinilla',
  'Medellín',
  'Montebello',
  'Murindó',
  'Mutatá',
  'Nariño',
  'Nechí',
  'Necoclí',
  'Olaya',
  'Peque',
  'Pueblorrico',
  'Puerto Berrío',
  'Puerto Nare',
  'Puerto Triunfo',
  'Remedios',
  'Rionegro',
  'Sabanalarga',
  'Sabaneta',
  'Salgar',
  'San Andrés de Cuerquia',
  'San Carlos',
  'San Francisco',
  'San Jerónimo',
  'San José de la Montaña',
  'San Juan de Urabá',
  'San Luis',
  'San Pedro',
  'San Pedro de Urabá',
  'San Rafael',
  'San Roque',
  'San Vicente',
  'Santa Bárbara',
  'Santa Fe de Antioquia',
  'Santa Rosa de Osos',
  'Santo Domingo',
  'Segovia',
  'Sonsón',
  'Sopetrán',
  'Támesis',
  'Tarazá',
  'Tarso',
  'Titiribí',
  'Toledo',
  'Turbo',
  'Uramita',
  'Urrao',
  'Valdivia',
  'Valparaíso',
  'Vegachí',
  'Venecia',
  'Vigía del Fuerte',
  'Yalí',
  'Yarumal',
  'Yolombó',
  'Yondó',
  'Zaragoza',
]